/**
 * Default P&ID node positions and edge definitions for Vue Flow.
 * These defaults are used when no saved layout exists on the backend.
 */

export const DEFAULT_NODES = [
    {
        id: 'component_a',
        type: 'feed',
        position: { x: 40, y: 20 },
        data: { feedType: 'component_a' },
    },
    {
        id: 'component_b',
        type: 'feed',
        position: { x: 280, y: 20 },
        data: { feedType: 'component_b' },
    },
    {
        id: 'solvent',
        type: 'feed',
        position: { x: 520, y: 20 },
        data: { feedType: 'solvent' },
    },
    {
        id: 'component_a_valve',
        type: 'instrument',
        position: { x: 40, y: 160 },
        data: { tag: 'XV-101', name: 'Component A Inlet Valve', valueKey: 'feed_rate_component_a', unit: 'kg/s' },
    },
    {
        id: 'component_a_pump',
        type: 'instrument',
        position: { x: 40, y: 270 },
        data: { tag: 'P-101', name: 'Component A Pump', valueKey: 'feed_rate_component_a', unit: 'kg/s' },
    },
    {
        id: 'component_a_flow',
        type: 'instrument',
        position: { x: 40, y: 380 },
        data: { tag: 'FT-101', name: 'Component A Flow', valueKey: 'feed_rate_component_a', unit: 'kg/s' },
    },
    {
        id: 'component_b_valve',
        type: 'instrument',
        position: { x: 280, y: 160 },
        data: { tag: 'XV-102', name: 'Component B Inlet Valve', valueKey: 'feed_rate_component_b', unit: 'kg/s' },
    },
    {
        id: 'component_b_pump',
        type: 'instrument',
        position: { x: 280, y: 270 },
        data: { tag: 'P-102', name: 'Component B Pump', valueKey: 'feed_rate_component_b', unit: 'kg/s' },
    },
    {
        id: 'component_b_flow',
        type: 'instrument',
        position: { x: 280, y: 380 },
        data: { tag: 'FT-102', name: 'Component B Flow', valueKey: 'feed_rate_component_b', unit: 'kg/s' },
    },
    {
        id: 'solvent_valve',
        type: 'instrument',
        position: { x: 520, y: 160 },
        data: { tag: 'XV-103', name: 'Solvent Inlet Valve', valueKey: 'feed_rate_solvent', unit: 'kg/s' },
    },
    {
        id: 'solvent_pump',
        type: 'instrument',
        position: { x: 520, y: 270 },
        data: { tag: 'P-103', name: 'Solvent Pump', valueKey: 'feed_rate_solvent', unit: 'kg/s' },
    },
    {
        id: 'solvent_flow',
        type: 'instrument',
        position: { x: 520, y: 380 },
        data: { tag: 'FT-103', name: 'Solvent Flow', valueKey: 'feed_rate_solvent', unit: 'kg/s' },
    },
    {
        id: 'reactor',
        type: 'reactor',
        position: { x: 220, y: 520 },
        data: {},
    },
    {
        id: 'temp_sensor',
        type: 'instrument',
        position: { x: 40, y: 560 },
        data: { tag: 'TT-101', name: 'Reactor Temp', valueKey: 'temperature_K', unit: 'K' },
    },
    {
        id: 'pressure_sensor',
        type: 'instrument',
        position: { x: 520, y: 560 },
        data: { tag: 'PT-101', name: 'Reactor Pressure', valueKey: 'pressure_bar', unit: 'bar' },
    },
    {
        id: 'level_sensor',
        type: 'instrument',
        position: { x: 220, y: 760 },
        data: { tag: 'LT-101', name: 'Reactor Fill Level', valueKey: 'fill_pct', unit: '%' },
    },
    {
        id: 'jacket',
        type: 'jacket',
        position: { x: 10, y: 830 },
        data: {},
    },
    {
        id: 'agitator',
        type: 'agitator',
        position: { x: 590, y: 830 },
        data: {},
    },
    {
        id: 'drain_valve',
        type: 'instrument',
        position: { x: 240, y: 900 },
        data: { tag: 'XV-301', name: 'Drain Valve', valueKey: 'mass_total_kg', unit: 'kg' },
    },
    {
        id: 'drain_pump',
        type: 'instrument',
        position: { x: 240, y: 1010 },
        data: { tag: 'P-301', name: 'Drain Pump', valueKey: 'mass_total_kg', unit: 'kg' },
    },
    {
        id: 'drain_flow',
        type: 'instrument',
        position: { x: 240, y: 1120 },
        data: { tag: 'FT-301', name: 'Drain Flow', valueKey: 'mass_total_kg', unit: 'kg' },
    },
    {
        id: 'product',
        type: 'product',
        position: { x: 240, y: 1250 },
        data: {},
    },
]

export const DEFAULT_EDGES = [
    {
        id: 'component_a-component_a_valve',
        source: 'component_a',
        target: 'component_a_valve',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_a', actuatorKey: 'feed_component_a' },
    },
    {
        id: 'component_a_valve-component_a_pump',
        source: 'component_a_valve',
        target: 'component_a_pump',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_a', actuatorKey: 'feed_component_a' },
    },
    {
        id: 'component_a_pump-component_a_flow',
        source: 'component_a_pump',
        target: 'component_a_flow',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_a' },
    },
    {
        id: 'component_a_flow-reactor',
        source: 'component_a_flow',
        target: 'reactor',
        sourceHandle: null,
        targetHandle: 'feed-top',
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_a' },
    },
    {
        id: 'component_b-component_b_valve',
        source: 'component_b',
        target: 'component_b_valve',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_b', actuatorKey: 'feed_component_b' },
    },
    {
        id: 'component_b_valve-component_b_pump',
        source: 'component_b_valve',
        target: 'component_b_pump',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_b', actuatorKey: 'feed_component_b' },
    },
    {
        id: 'component_b_pump-component_b_flow',
        source: 'component_b_pump',
        target: 'component_b_flow',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_b' },
    },
    {
        id: 'component_b_flow-reactor',
        source: 'component_b_flow',
        target: 'reactor',
        sourceHandle: null,
        targetHandle: 'feed-center',
        type: 'pipe',
        data: { flowKey: 'feed_rate_component_b' },
    },
    {
        id: 'solvent-solvent_valve',
        source: 'solvent',
        target: 'solvent_valve',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_solvent', actuatorKey: 'feed_solvent' },
    },
    {
        id: 'solvent_valve-solvent_pump',
        source: 'solvent_valve',
        target: 'solvent_pump',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_solvent', actuatorKey: 'feed_solvent' },
    },
    {
        id: 'solvent_pump-solvent_flow',
        source: 'solvent_pump',
        target: 'solvent_flow',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { flowKey: 'feed_rate_solvent' },
    },
    {
        id: 'solvent_flow-reactor',
        source: 'solvent_flow',
        target: 'reactor',
        sourceHandle: null,
        targetHandle: 'feed-right',
        type: 'pipe',
        data: { flowKey: 'feed_rate_solvent' },
    },
    {
        id: 'reactor-drain_valve',
        source: 'reactor',
        target: 'drain_valve',
        sourceHandle: 'product',
        targetHandle: null,
        type: 'pipe',
        data: {},
    },
    {
        id: 'drain_valve-drain_pump',
        source: 'drain_valve',
        target: 'drain_pump',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: {},
    },
    {
        id: 'drain_pump-drain_flow',
        source: 'drain_pump',
        target: 'drain_flow',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: {},
    },
    {
        id: 'drain_flow-product',
        source: 'drain_flow',
        target: 'product',
        sourceHandle: null,
        targetHandle: null,
        type: 'pipe',
        data: { valveTag: 'PV-201' },
    },
    {
        id: 'jacket-reactor',
        source: 'jacket',
        target: 'reactor',
        sourceHandle: null,
        targetHandle: 'jacket',
        type: 'pipe',
        data: { valveTag: 'TV-101', actuatorKey: 'jacket_temp' },
    },
    {
        id: 'agitator-reactor',
        source: 'agitator',
        target: 'reactor',
        sourceHandle: null,
        targetHandle: 'agitator',
        type: 'pipe',
        // No valve — agitator shaft is a mechanical connection, not a pipe
        data: { noArrow: true },
    },
]
